env:
  browser: true
  es2021: true
  node: true
  'vue/setup-compiler-macros': true,
extends:
  - eslint:recommended  # eslint 推荐规则
  - plugin:vue/vue3-recommended # vue3 规则
  - plugin:@typescript-eslint/recommended # typescript的规则集
  - plugin:prettier/recommended # 解决eslint 和 prettier的冲突
parser: vue-eslint-parser
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
rules: {
  '@typescript-eslint/no-var-requires': 'off',
  '@typescript-eslint/no-explicit-any': 'off',
  'vue/multi-word-component-names': 'off',
}
